### ISSUE TITLE
ImportError: cannot import name 'safety_check' from 'app'

### ISSUE THREAD

**Issue by CRCODE22** [NVlabs/Sana#41]
(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
Traceback (most recent call last):
  File "K:\Sana\app\app_sana.py", line 34, in <module>
    from app import safety_check
ImportError: cannot import name 'safety_check' from 'app' (e:\anaconda3\envs\sana\lib\site-packages\app\__init__.py)

**Comment by lawrence-cj** [comment]
Have you followed the env installation step by step?

**Comment by CRCODE22** [comment]
> Have you followed the env installation step by step?

Yes I did.

**Comment by lawrence-cj** [comment]
pull the latest code

**Comment by CRCODE22** [comment]
This is not fixed @yujincheng08 @lawrence-cj it does not work pulling the latest code does not solve it. Please come with suggestions that do work.

Here is what I did on Windows 11:

git clone https://github.com/NVlabs/Sana.git
conda create -n sana python=3.10.0 -y
conda activate sana
conda install -c nvidia cuda-toolkit -y
python -m pip install -U pip
pip install -U xformers==0.0.27.post2 --index-url https://download.pytorch.org/whl/cu121
pip install -e .
ERROR: Could not find a version that satisfies the requirement triton==3.0.0 (from sana) (from versions: none)
ERROR: No matching distribution found for triton==3.0.0

**Comment by CRCODE22** [comment]
This is the first model that does not work on Windows 11: Flux, SD1.5, SDXL etc they all work pretty much upon release and their developers actually know how to make them work on Windows 11.

**Comment by CRCODE22** [comment]
It does not look like anymore this model is even worth spending all that time on getting to work after days it still does not. Their devs clearly do not even know how to get it running on Windows 11.

pip install gradio

(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
Traceback (most recent call last):
  File "K:\Sana\app\app_sana.py", line 30, in <module>
    import spaces
ModuleNotFoundError: No module named 'spaces'

(sana) K:\Sana>pip install spaces


(sana) K:\Sana>python app\app_sana.py --config configs\sana_config\1024ms\Sana_1600M_img1024.yaml --model_path Efficient-Large-Model\Sana_1600M_1024px\checkpoints\Sana_1600M_1024px.pth
Traceback (most recent call last):
  File "K:\Sana\app\app_sana.py", line 33, in <module>
    from torchvision.utils import make_grid, save_image
ModuleNotFoundError: No module named 'torchvision'

(sana) K:\Sana>pip install torchvision

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.27.post2 requires torch==2.4.0, but you have torch 2.5.1 which is incompatible.
Successfully installed torch-2.5.1 torchvision-0.20.1

**Comment by alexcardo** [comment]
Same for me:

```
(base) alex@NLDW4-5-20-11:~/ai/Sana$ DEMO_PORT=15432 python app/app_sana.py     --share     --config=configs/sana_config/1024ms/Sana_1600M_img1024.yaml     --model_path=/home/alex/ai/Sana_600M_512px/checkpoints/Sana_600M_512px_MultiLing.pth
Traceback (most recent call last):
  File "/home/alex/ai/Sana/app/app_sana.py", line 36, in <module>
    from app import safety_check
ImportError: cannot import name 'safety_check' from 'app' (/home/alex/miniconda3/lib/python3.12/site-packages/app/__init__.py)
(base) alex@NLDW4-5-20-11:~/ai/Sana$ nano /home/alex/ai/Sana/app/app_sana.py
(base) alex@NLDW4-5-20-11:~/ai/Sana$ git pull https://github.com/NVlabs/Sana
From https://github.com/NVlabs/Sana
 * branch            HEAD       -> FETCH_HEAD
Already up to date.
(base) alex@NLDW4-5-20-11:~/ai/Sana$
```

**Comment by FurkanGozukara** [comment]
I made it work on Windows, RunPod official pytorch template, Massed compute and Kaggle

all editable scripts you can use as you wish

https://www.patreon.com/posts/from-nvidia-labs-116474081

![001](https://github.com/user-attachments/assets/61f1300c-1a79-408a-a82b-09ccf0503363)

![01](https://github.com/user-attachments/assets/03e4af47-a568-4168-85d5-3c4041a8bfaf)

![05](https://github.com/user-attachments/assets/64efdf52-86cf-488d-a765-40c5c1441552)
